/// Listing - merchant menu items and their priced variants.
///
/// A `Listing` represents one menu entry (e.g. "Black Coffee") and holds a map
/// of priced `Variant`s keyed by their auto-generated `ID` (e.g. S/M/L). Each
/// variant carries a stablecoin `price` and an optional `loyalty_price`, allowing
/// customers to pay in either currency. Listings live as values inside
/// `Merchant.listings` - they do not exist independently of their owning Merchant.
module openzeppelin_payments::listing;

use std::string::String;
use sui::vec_map::{Self, VecMap};

// === Errors ===

#[error(code = 0)]
const EEmptyName: vector<u8> = "Name cannot be empty";
#[error(code = 1)]
const EZeroPrice: vector<u8> = "Price must be greater than zero";
#[error(code = 2)]
const EVariantNotFound: vector<u8> = "Listing variant not found";
#[error(code = 3)]
const EActiveStateUnchanged: vector<u8> = "Listing already has the requested active state";

// === Structs ===

/// A menu entry. Holds zero-or-more priced variants and an `active` toggle.
///
/// The listing's stable ID is the key it lives under in `Merchant.listings`; it
/// is generated at insert time (see `merchant::add_listing`) and is not stored
/// on the struct itself.
public struct Listing has drop, store {
    /// Display name (e.g. "Black Coffee").
    name: String,
    /// Priced variants, keyed by their auto-generated `ID`.
    variants: VecMap<ID, Variant>,
    /// Whether this listing is currently purchasable (display hint).
    active: bool,
}

/// A priced variant of a Listing (e.g. a size).
///
/// The variant's stable ID is the key it lives under in `Listing.variants` (and
/// `Merchant.variant_index`); it is generated at insert time (see `add_variant`)
/// and is not stored on the struct itself.
public struct Variant has drop, store {
    /// Display name (e.g. "Small").
    name: String,
    /// Stablecoin price in token units.
    price: u64,
    /// Optional LOYALTY price. `None` means this variant cannot be paid for in
    /// LOYALTY (voucher creation aborts with `receipt::ENoLoyaltyPrice`).
    loyalty_price: Option<u64>,
}

// === Public Functions ===

/// Construct a Listing with no variants.
///
/// Variants are added post-construction via `add_variant`. The listing's key is
/// generated when it is stored on a `Merchant` via `merchant::add_listing`.
///
/// #### Parameters
/// - `name`: Display name (e.g. "Black Coffee"). Must be non-empty.
///
/// #### Returns
/// - The constructed `Listing`, marked `active`.
///
/// #### Aborts
/// - `EEmptyName` if `name` is empty.
public fun new(name: String): Listing {
    assert!(!name.is_empty(), EEmptyName);

    Listing { name, variants: vec_map::empty(), active: true }
}

/// Construct a `Variant`. Its key is generated when it is inserted into a
/// Listing via `add_variant`.
///
/// #### Parameters
/// - `name`: Display name (e.g. "Small"). Must be non-empty.
/// - `price`: Stablecoin price in token units. Must be non-zero.
/// - `loyalty_price`: Optional LOYALTY price. If `Some`, Must be non-zero; `None`
///   means the variant cannot be redeemed for loyalty.
///
/// #### Returns
/// - The constructed `Variant`.
///
/// #### Aborts
/// - `EEmptyName` if `name` is empty.
/// - `EZeroPrice` if `price` is zero, or if `loyalty_price` is `Some(0)`.
public fun new_variant(name: String, price: u64, loyalty_price: Option<u64>): Variant {
    assert!(!name.is_empty(), EEmptyName);
    assert!(price > 0, EZeroPrice);
    if (loyalty_price.is_some()) {
        assert!(*loyalty_price.borrow() > 0, EZeroPrice);
    };

    Variant { name, price, loyalty_price }
}

// === View Functions ===

/// Display name of the listing (e.g. "Black Coffee").
public fun name(self: &Listing): &String { &self.name }

/// All variants on this listing, keyed by variant ID.
public fun variants(self: &Listing): &VecMap<ID, Variant> { &self.variants }

/// Look up a variant by ID.
///
/// #### Parameters
/// - `self`: The listing to read.
/// - `variant`: ID of the variant to look up.
///
/// #### Returns
/// - Reference to the matching `Variant`.
///
/// #### Aborts
/// - `EVariantNotFound` if no variant with `variant` exists on this listing.
public fun variant(self: &Listing, variant: &ID): &Variant {
    assert!(self.variants.contains(variant), EVariantNotFound);

    self.variants.get(variant)
}

/// Whether the listing is purchasable.
public fun active(self: &Listing): bool { self.active }

/// Display name of the variant (e.g. "Small").
public fun variant_name(self: &Variant): &String { &self.name }

/// Stablecoin price in token units.
public fun price(self: &Variant): u64 { self.price }

/// Optional price in `LOYALTY` units. `None` if the variant cannot be paid in loyalty.
public fun loyalty_price(self: &Variant): Option<u64> { self.loyalty_price }

// === Package Functions ===

/// Insert a variant under the given key.
///
/// The key is generated by the caller (see `merchant::add_listing_variant`),
/// which also uses it to register the variant in `Merchant.variant_index`.
///
/// #### Parameters
/// - `self`: The listing to mutate.
/// - `variant`: The variant to insert.
/// - `id`: The key to store the variant under.
///
/// #### Aborts
/// - Aborts (via `vec_map::insert`) if `id` already exists in this listing.
public(package) fun add_variant(self: &mut Listing, variant: Variant, id: ID) {
    self.variants.insert(id, variant);
}

/// Remove a variant by ID.
///
/// #### Parameters
/// - `self`: The listing to mutate.
/// - `variant_id`: ID of the variant to remove.
///
/// #### Aborts
/// - `EVariantNotFound` if no variant with `variant_id` exists on this listing.
public(package) fun remove_variant(self: &mut Listing, variant_id: ID) {
    assert!(self.variants.contains(&variant_id), EVariantNotFound);

    let (_, _) = self.variants.remove(&variant_id);
}

/// Toggle whether this listing is purchasable.
///
/// #### Parameters
/// - `self`: The listing to mutate.
/// - `active`: The new active state.
///
/// #### Aborts
/// - `EActiveStateUnchanged` if `active` already matches the current state.
public(package) fun set_active(self: &mut Listing, active: bool) {
    assert!(self.active != active, EActiveStateUnchanged);

    self.active = active;
}
